// This file is auto-generated by Fresh.
// Do not modify this file manually.

import * as $0 from "./routes/connections.ts";
import * as $1 from "./routes/export.ts";
import * as $2 from "./routes/tables.ts";
import * as $3 from "./routes/templates.ts";
import * as $4 from "./routes/visualizations.ts";
import * as errorHandler from "./middleware/errorHandler.ts";
import * as notFoundHandler from "./middleware/errorHandler.ts";

const manifest = {
  routes: {
    "./routes/connections.ts": $0,
    "./routes/export.ts": $1,
    "./routes/tables.ts": $2,
    "./routes/templates.ts": $3,
    "./routes/visualizations.ts": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
  middlewares: {
    error: errorHandler,
    notFound: notFoundHandler,
  }
};

export default manifest;
